### ISSUE TITLE
issue using converted vnect.pkl 

### ISSUE THREAD

**Issue by mlasy** [timctho/VNect-tensorflow#11]
i converted the caffemodel using the caffe_weights_to_pickle.py.
however, when i want to load the vnect.pkl with tensorflow, i get:
`DataLossError (see above for traceback): Unable to open table file models/weights/vnect_tf: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?`

thanks for any help

**Comment by yukaliu07** [comment]
check vnect_model.py in the models folder. But I am not sure should we directly save the model from there.

**Comment by lavage** [comment]
@yukaliu07 could you maybe explain how/where to use saver.save?

**Comment by lavage** [comment]
@yukaliu07 could you maybe provide some more detail on how to use saver.save? I have implemented it as follows, but the model files that this returns, give me wrong results:


    with tf.Session() as sess:
        saver = tf.train.Saver()
        tf_writer = tf.summary.FileWriter(logdir='./', graph=sess.graph)

        sess.run(tf.global_variables_initializer())
        saver.save(sess, './vnect_tf')
        print(model.res5b_branch2c_new)
        print(model.heatmap, model.x_heatmap, model.y_heatmap, model.z_heatmap)

**Comment by yukaliu07** [comment]
@lavage 
`with tf.Session() as sess:
        saver = tf.train.Saver()
	model.load_weights(sess, model_file)
	save_path = saver.save(sess, "./vnect_tf")`

**Comment by fenglupeter** [comment]
@yukaliu07 
I use the code but the pkl can't convert correctly.
Error message:
Traceback (most recent call last):
  File "models/vnect_model.py", line 175, in <module>
    model = VNect(368)
  File "models/vnect_model.py", line 13, in __init__
    self._create_network()
  File "models/vnect_model.py", line 94, in _create_network
    self.res4d_branch2a = tc.lvnectayers.conv2d(self.res4c, kernel_size=1, num_outputs=256, scope='res4d_branch2a')
AttributeError: 'module' object has no attribute 'lvnectayers'

**Comment by Robinchacko** [comment]
Hello,
I had tried this code with these follows.

    1.Download weights from the author of paper
    2.change weights with using './caffe_weight_to_pickle.py'
   3. run '/models/vnect_model.py' to get

   

> vnect_tf.data-00000-of-00001
>    vnect_tf.index
>    vnect_tf.meta

    
    run '/demo_tf.py'

But I am getting an error like this
`2018-09-27 16:11:48.784541: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open models/weights/vnect_tf: Failed precondition: models/weights/vnect_tf; Is a directory: perhaps your file is in a different file format and you need to use a different restore operator?`

**Comment by powermew** [comment]
@Robinchacko
At step 3 on your method, i guess you should fix the location of model file in demo_tf.py

**Comment by powermew** [comment]
I changed code line 173-181 in **vnect_tf.py**

```
if __name__ == '__main__':
    model_file = 'vnect.pkl'
    model = VNect(368)

    with tf.Session() as sess:
        saver = tf.train.Saver()
        model.load_weights(sess, model_file)
        save_path = saver.save(sess, "./vnect_tf")
```

**Comment by Robinchacko** [comment]
@powermew Thanks for the reply. I have tried the methods that you have mentioned . But couldn't solve the problem. Could you please send me the files that you have edited.
[robinchacko1192@gmail.com ] .

**Comment by musab1234** [comment]
can any one provide model files please? musab@wondertree.co , author is not replying.

**Comment by rafikg** [comment]
@musab1234,
Hi, did you get the model files? Could you share it?

**Comment by faybak** [comment]
Can you send your weight and model files?I have sent a email to the author since last week, but he haven't replied yet. my email is fayadbakary@gmail.com

**Comment by linche1** [comment]
can you send the weight and model file? much appreciation!! 2448398161@qq.com

**Comment by funnyQZQ** [comment]
Can you send the weight and the model file? Much appreciation!! [funnyqzq@gmail.com](mailto:funnyqzq@gmail.com)
