### ISSUE TITLE
I am getting this error . aseOperation = baseOperation, OpenGL.error.GLError: GLError(         err = 1282,         description = b'invalid operation',         baseOperation = glMatrixMode,         cArguments = (GL_PROJECTION,) ) ? please help me

### ISSUE THREAD

**Issue by TechRova** [timctho/VNect-tensorflow#28]
Config:

- Win 10 
- python 3.7
- Logitech C270 webcam

```
PS C:\Users\TechRova\Downloads\VNect-tensorflow-master> python demo_tf_gl.py --device=gpu --demo_type=webcam --test_img=
test_imgs/yuniko.jpg --model_file=models/weights/vnect_tf  --plot_2d=True --plot_3d=True
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "demo_tf_gl.py", line 247, in <module>
    glMatrixMode(GL_PROJECTION)
  File "C:\Users\TechRova\AppData\Local\Programs\Python\Python37\lib\site-packages\OpenGL\platform\baseplatform.py", line 409, in __call__
    return self( *args, **named )
  File "C:\Users\TechRova\AppData\Local\Programs\Python\Python37\lib\site-packages\OpenGL\error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
        err = 1282,
        description = b'invalid operation',
        baseOperation = glMatrixMode,
        cArguments = (GL_PROJECTION,)
)
```

**Comment by xuzheyuan624** [comment]
@TechRova I meet the same problem, have u solved it ?

**Comment by suly520** [comment]
Same problem! My Program works on Windows perfectly on Raspberry(Linux) i get the same Problem ( I am using python 3.9.4 on Windows works on 3.6 i think on raspi dont works :/)
